# Generated by Django 4.0.5 on 2022-06-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registroUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16, verbose_name='usuario')),
                ('nombre', models.CharField(max_length=16, verbose_name='nombre del usuario')),
                ('apellidoPaterno', models.CharField(max_length=16, verbose_name='apellido paterno del ususario')),
                ('apellidoMaterno', models.CharField(max_length=16, verbose_name='apellido materno del usuario')),
                ('contrasena', models.CharField(max_length=12, verbose_name='contraseña del usuario')),
                ('correo', models.CharField(max_length=40, verbose_name='correo del usuario')),
                ('telefono', models.IntegerField(verbose_name='telefono del usuario')),
                ('nombreMascota', models.CharField(max_length=16, verbose_name='nombre de la mascota')),
                ('edadMascota', models.IntegerField(verbose_name='edad de la mascota')),
            ],
        ),
    ]
