# Generated by Django 4.0.5 on 2022-07-08 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apoderado',
            fields=[
                ('rutApo', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Rut Apoderado')),
                ('nombreApo', models.CharField(max_length=50, verbose_name='Nombre Apoderado')),
                ('apellidoApo', models.CharField(max_length=50, verbose_name='Apellido Apoderado')),
                ('telefonoAapo', models.IntegerField(verbose_name='Tefefono Apoderado')),
                ('direccionApo', models.CharField(max_length=100, verbose_name='Direccion Apoderado')),
                ('emailApo', models.CharField(max_length=50, verbose_name='Email Apoderado')),
            ],
        ),
        migrations.CreateModel(
            name='registroMascotas',
            fields=[
                ('idChip', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del chip de tu mascota')),
                ('nombreMascota', models.CharField(max_length=50, verbose_name='Nombre de tu mascota')),
                ('edadMascota', models.IntegerField(verbose_name='Edad de tu mascota')),
                ('sexo', models.IntegerField(choices=[[0, 'Macho'], [1, 'Hembra']])),
                ('tipoMascota', models.IntegerField(choices=[[0, 'Perros'], [1, 'Gatos'], [2, 'Aves'], [3, 'Otros']])),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apoderado')),
            ],
        ),
    ]
