# Generated by Django 4.0.5 on 2022-06-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registroMascotas',
            fields=[
                ('idChip', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del chip de tu mascota')),
                ('nombreMascota', models.CharField(max_length=50, verbose_name='Nombre de tu mascota')),
                ('edadMascota', models.IntegerField(verbose_name='Edad de tu mascota')),
                ('tipoMascota', models.IntegerField(choices=[[0, 'Perros'], [1, 'Gatos'], [2, 'Aves'], [3, 'Otros']])),
            ],
        ),
    ]
